CREATE SCHEMA MED_JOURNALS;
SET SCHEMA MED_JOURNALS;

CREATE TABLE USERS (
		ID INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1) CONSTRAINT UPK PRIMARY KEY,
		EMAIL VARCHAR(128) NOT NULL,
		JOURNAL_NAME VARCHAR(256) NOT NULL,
		PASSWORD VARCHAR(20) NOT NULL
);
